[build]
  publish = "public"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "14"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200